Code improvement and gitignore
zshannon/cloudwatchlogger pull request #6
Opened 2018-07-09 07:47 UTC by luizkowalski

2018-07-10 04:01 UTC, zshannon requested changes
Are you using an automated formatter? It'd be nice to include the formatting preferences you've got in a reproducible, consistent way. I'm okay with accepting arbitrary syntax formatting changes if they reduce the entropy of the project overall.

2018-07-10 04:01 UTC, zshannon commented on lib/cloudwatchlogger/client/aws_sdk/threaded.rb
> +          @opts = opts
AFAIK, need to wait until we're done mutating `opts` (next two lines) before we store it on the class. Whether this is true or not, I'd like the code to read consistently so it's obvious we intend to be concerned with one object here.

2018-07-10 07:23 UTC, luizkowalski commented on lib/cloudwatchlogger/client/aws_sdk/threaded.rb
> +          @opts = opts
> need to wait until we're done mutating opts (next two lines) before we store it on the class

but the code was not doing this before anyway...this was just a parallel assignment that I broke down into multiple lines to better reading. If you think that `opts` should be mutate *before* assign I can move up the next two lines

2018-07-10 07:25 UTC, luizkowalski commented
I'm not using any code formatter but I'm fine with adding something like `.editorconfig` though I would do it in another PR

2018-07-10 16:23 UTC, zshannon commented
I was thinking something like [rubocop](https://rubocop.readthedocs.io/en/latest/) to encore their [community style guide](https://github.com/rubocop-hq/ruby-style-guide). Are you game to set that up?

2018-07-10 16:25 UTC, zshannon commented on lib/cloudwatchlogger/client/aws_sdk/threaded.rb
> +          @opts = opts
I do think `opts` should be mutated before assigning it off to the class.  Moving the mutation up is 👍

2018-07-11 11:21 UTC, luizkowalski commented
yes, I'll set up Rubocop in another PR later this week

2018-07-11 15:02 UTC, zshannon approved these changes

2018-07-11 15:02 UTC, merged